version: '3' 
services: 
  favorites_browser: 
    build: app
    ports: 
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:${DB_PASSWORD}@db/postgres
      - DEBUG=${DEBUG}
      - FLICKR_KEY=${FLICKR_KEY}
    networks:
      - service-network
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - service-network
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
networks:
  service-network: {}
volumes:
  pg-data: {}
